// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products-delete": {
    params: {};
  };
  "/webhooks/products": {
    params: {};
  };
  "/styles/index": {
    params: {};
  };
  "/api/analyze": {
    params: {};
  };
  "/api/credits": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/api/campaign-manage": {
    params: {};
  };
  "/app/api/campaign-status": {
    params: {};
  };
  "/app/api/store-analytics": {
    params: {};
  };
  "/app/api/market-intel": {
    params: {};
  };
  "/app/api/subscription": {
    params: {};
  };
  "/app/api/ai-improve": {
    params: {};
  };
  "/app/api/job-status": {
    params: {};
  };
  "/app/api/ai-engine": {
    params: {};
  };
  "/app/api/campaign": {
    params: {};
  };
  "/app/api/keywords": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/api/health": {
    params: {};
  };
  "/app/api/state": {
    params: {};
  };
  "/app/campaigns": {
    params: {};
  };
  "/app/api/scan": {
    params: {};
  };
  "/app/api/sync": {
    params: {};
  };
  "/app/keywords": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/saved": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/products-delete" | "/webhooks/products" | "/styles/index" | "/api/analyze" | "/api/credits" | "/api/health" | "/auth/login" | "/auth/*" | "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/store-analytics" | "/app/api/market-intel" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/job-status" | "/app/api/ai-engine" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/api/health" | "/app/api/state" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products-delete.tsx": {
    id: "routes/webhooks.products-delete";
    page: "/webhooks/products-delete";
  };
  "routes/webhooks.products.tsx": {
    id: "routes/webhooks.products";
    page: "/webhooks/products";
  };
  "routes/styles.index.js": {
    id: "routes/styles.index";
    page: "/styles/index";
  };
  "routes/api.analyze.js": {
    id: "routes/api.analyze";
    page: "/api/analyze";
  };
  "routes/api.credits.jsx": {
    id: "routes/api.credits";
    page: "/api/credits";
  };
  "routes/api.health.js": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/store-analytics" | "/app/api/market-intel" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/job-status" | "/app/api/ai-engine" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/api/health" | "/app/api/state" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/app.api.campaign-manage.ts": {
    id: "routes/app.api.campaign-manage";
    page: "/app/api/campaign-manage";
  };
  "routes/app.api.campaign-status.ts": {
    id: "routes/app.api.campaign-status";
    page: "/app/api/campaign-status";
  };
  "routes/app.api.store-analytics.ts": {
    id: "routes/app.api.store-analytics";
    page: "/app/api/store-analytics";
  };
  "routes/app.api.market-intel.ts": {
    id: "routes/app.api.market-intel";
    page: "/app/api/market-intel";
  };
  "routes/app.api.subscription.ts": {
    id: "routes/app.api.subscription";
    page: "/app/api/subscription";
  };
  "routes/app.api.ai-improve.ts": {
    id: "routes/app.api.ai-improve";
    page: "/app/api/ai-improve";
  };
  "routes/app.api.job-status.ts": {
    id: "routes/app.api.job-status";
    page: "/app/api/job-status";
  };
  "routes/app.api.ai-engine.ts": {
    id: "routes/app.api.ai-engine";
    page: "/app/api/ai-engine";
  };
  "routes/app.api.campaign.ts": {
    id: "routes/app.api.campaign";
    page: "/app/api/campaign";
  };
  "routes/app.api.keywords.ts": {
    id: "routes/app.api.keywords";
    page: "/app/api/keywords";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.api.health.ts": {
    id: "routes/app.api.health";
    page: "/app/api/health";
  };
  "routes/app.api.state.ts": {
    id: "routes/app.api.state";
    page: "/app/api/state";
  };
  "routes/app.campaigns.tsx": {
    id: "routes/app.campaigns";
    page: "/app/campaigns";
  };
  "routes/app.api.scan.ts": {
    id: "routes/app.api.scan";
    page: "/app/api/scan";
  };
  "routes/app.api.sync.ts": {
    id: "routes/app.api.sync";
    page: "/app/api/sync";
  };
  "routes/app.keywords.tsx": {
    id: "routes/app.keywords";
    page: "/app/keywords";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.saved.tsx": {
    id: "routes/app.saved";
    page: "/app/saved";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.products-delete": typeof import("./app/routes/webhooks.products-delete.tsx");
  "routes/webhooks.products": typeof import("./app/routes/webhooks.products.tsx");
  "routes/styles.index": typeof import("./app/routes/styles.index.js");
  "routes/api.analyze": typeof import("./app/routes/api.analyze.js");
  "routes/api.credits": typeof import("./app/routes/api.credits.jsx");
  "routes/api.health": typeof import("./app/routes/api.health.js");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.api.campaign-manage": typeof import("./app/routes/app.api.campaign-manage.ts");
  "routes/app.api.campaign-status": typeof import("./app/routes/app.api.campaign-status.ts");
  "routes/app.api.store-analytics": typeof import("./app/routes/app.api.store-analytics.ts");
  "routes/app.api.market-intel": typeof import("./app/routes/app.api.market-intel.ts");
  "routes/app.api.subscription": typeof import("./app/routes/app.api.subscription.ts");
  "routes/app.api.ai-improve": typeof import("./app/routes/app.api.ai-improve.ts");
  "routes/app.api.job-status": typeof import("./app/routes/app.api.job-status.ts");
  "routes/app.api.ai-engine": typeof import("./app/routes/app.api.ai-engine.ts");
  "routes/app.api.campaign": typeof import("./app/routes/app.api.campaign.ts");
  "routes/app.api.keywords": typeof import("./app/routes/app.api.keywords.ts");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.api.health": typeof import("./app/routes/app.api.health.ts");
  "routes/app.api.state": typeof import("./app/routes/app.api.state.ts");
  "routes/app.campaigns": typeof import("./app/routes/app.campaigns.tsx");
  "routes/app.api.scan": typeof import("./app/routes/app.api.scan.ts");
  "routes/app.api.sync": typeof import("./app/routes/app.api.sync.ts");
  "routes/app.keywords": typeof import("./app/routes/app.keywords.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.saved": typeof import("./app/routes/app.saved.tsx");
};