// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products-delete": {
    params: {};
  };
  "/webhooks/products": {
    params: {};
  };
  "/api/analyze": {
    params: {};
  };
  "/api/credits": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/api/campaign-manage": {
    params: {};
  };
  "/app/api/campaign-status": {
    params: {};
  };
  "/app/api/subscription": {
    params: {};
  };
  "/app/api/ai-improve": {
    params: {};
  };
  "/app/api/campaign": {
    params: {};
  };
  "/app/api/keywords": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/campaigns": {
    params: {};
  };
  "/app/api/scan": {
    params: {};
  };
  "/app/api/sync": {
    params: {};
  };
  "/app/keywords": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/saved": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/products-delete" | "/webhooks/products" | "/api/analyze" | "/api/credits" | "/auth/login" | "/auth/*" | "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products-delete.jsx": {
    id: "routes/webhooks.products-delete";
    page: "/webhooks/products-delete";
  };
  "routes/webhooks.products.jsx": {
    id: "routes/webhooks.products";
    page: "/webhooks/products";
  };
  "routes/api.analyze.js": {
    id: "routes/api.analyze";
    page: "/api/analyze";
  };
  "routes/api.credits.jsx": {
    id: "routes/api.credits";
    page: "/api/credits";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/app.api.campaign-manage.js": {
    id: "routes/app.api.campaign-manage";
    page: "/app/api/campaign-manage";
  };
  "routes/app.api.campaign-status.js": {
    id: "routes/app.api.campaign-status";
    page: "/app/api/campaign-status";
  };
  "routes/app.api.subscription.js": {
    id: "routes/app.api.subscription";
    page: "/app/api/subscription";
  };
  "routes/app.api.ai-improve.js": {
    id: "routes/app.api.ai-improve";
    page: "/app/api/ai-improve";
  };
  "routes/app.api.campaign.js": {
    id: "routes/app.api.campaign";
    page: "/app/api/campaign";
  };
  "routes/app.api.keywords.js": {
    id: "routes/app.api.keywords";
    page: "/app/api/keywords";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.campaigns.jsx": {
    id: "routes/app.campaigns";
    page: "/app/campaigns";
  };
  "routes/app.api.scan.js": {
    id: "routes/app.api.scan";
    page: "/app/api/scan";
  };
  "routes/app.api.sync.js": {
    id: "routes/app.api.sync";
    page: "/app/api/sync";
  };
  "routes/app.keywords.jsx": {
    id: "routes/app.keywords";
    page: "/app/keywords";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.saved.jsx": {
    id: "routes/app.saved";
    page: "/app/saved";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.products-delete": typeof import("./app/routes/webhooks.products-delete.jsx");
  "routes/webhooks.products": typeof import("./app/routes/webhooks.products.jsx");
  "routes/api.analyze": typeof import("./app/routes/api.analyze.js");
  "routes/api.credits": typeof import("./app/routes/api.credits.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.api.campaign-manage": typeof import("./app/routes/app.api.campaign-manage.js");
  "routes/app.api.campaign-status": typeof import("./app/routes/app.api.campaign-status.js");
  "routes/app.api.subscription": typeof import("./app/routes/app.api.subscription.js");
  "routes/app.api.ai-improve": typeof import("./app/routes/app.api.ai-improve.js");
  "routes/app.api.campaign": typeof import("./app/routes/app.api.campaign.js");
  "routes/app.api.keywords": typeof import("./app/routes/app.api.keywords.js");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.campaigns": typeof import("./app/routes/app.campaigns.jsx");
  "routes/app.api.scan": typeof import("./app/routes/app.api.scan.js");
  "routes/app.api.sync": typeof import("./app/routes/app.api.sync.js");
  "routes/app.keywords": typeof import("./app/routes/app.keywords.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.saved": typeof import("./app/routes/app.saved.jsx");
};