// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products-delete": {
    params: {};
  };
  "/CollectingDataScreen": {
    params: {};
  };
  "/CompetitorComponents": {
    params: {};
  };
  "/LandingComponents": {
    params: {};
  };
  "/webhooks/products": {
    params: {};
  };
  "/DashboardWidgets": {
    params: {};
  };
  "/SmallComponents": {
    params: {};
  };
  "/AdPreviewPanel": {
    params: {};
  };
  "/StoreAnalytics": {
    params: {};
  };
  "/styles/index": {
    params: {};
  };
  "/api/analyze": {
    params: {};
  };
  "/api/credits": {
    params: {};
  };
  "/MarketAlert": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/api/campaign-manage": {
    params: {};
  };
  "/app/api/campaign-status": {
    params: {};
  };
  "/app/api/store-analytics": {
    params: {};
  };
  "/app/api/market-intel": {
    params: {};
  };
  "/app/api/subscription": {
    params: {};
  };
  "/app/api/ai-improve": {
    params: {};
  };
  "/app/api/ai-engine": {
    params: {};
  };
  "/app/api/campaign": {
    params: {};
  };
  "/app/api/keywords": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/api/state": {
    params: {};
  };
  "/app/campaigns": {
    params: {};
  };
  "/app/api/scan": {
    params: {};
  };
  "/app/api/sync": {
    params: {};
  };
  "/app/keywords": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/saved": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/products-delete" | "/CollectingDataScreen" | "/CompetitorComponents" | "/LandingComponents" | "/webhooks/products" | "/DashboardWidgets" | "/SmallComponents" | "/AdPreviewPanel" | "/StoreAnalytics" | "/styles/index" | "/api/analyze" | "/api/credits" | "/MarketAlert" | "/auth/login" | "/auth/*" | "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/store-analytics" | "/app/api/market-intel" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/ai-engine" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/api/state" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products-delete.jsx": {
    id: "routes/webhooks.products-delete";
    page: "/webhooks/products-delete";
  };
  "routes/CollectingDataScreen.jsx": {
    id: "routes/CollectingDataScreen";
    page: "/CollectingDataScreen";
  };
  "routes/CompetitorComponents.jsx": {
    id: "routes/CompetitorComponents";
    page: "/CompetitorComponents";
  };
  "routes/LandingComponents.jsx": {
    id: "routes/LandingComponents";
    page: "/LandingComponents";
  };
  "routes/webhooks.products.jsx": {
    id: "routes/webhooks.products";
    page: "/webhooks/products";
  };
  "routes/DashboardWidgets.jsx": {
    id: "routes/DashboardWidgets";
    page: "/DashboardWidgets";
  };
  "routes/SmallComponents.jsx": {
    id: "routes/SmallComponents";
    page: "/SmallComponents";
  };
  "routes/AdPreviewPanel.jsx": {
    id: "routes/AdPreviewPanel";
    page: "/AdPreviewPanel";
  };
  "routes/StoreAnalytics.jsx": {
    id: "routes/StoreAnalytics";
    page: "/StoreAnalytics";
  };
  "routes/styles.index.js": {
    id: "routes/styles.index";
    page: "/styles/index";
  };
  "routes/api.analyze.js": {
    id: "routes/api.analyze";
    page: "/api/analyze";
  };
  "routes/api.credits.jsx": {
    id: "routes/api.credits";
    page: "/api/credits";
  };
  "routes/MarketAlert.jsx": {
    id: "routes/MarketAlert";
    page: "/MarketAlert";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/api/campaign-manage" | "/app/api/campaign-status" | "/app/api/store-analytics" | "/app/api/market-intel" | "/app/api/subscription" | "/app/api/ai-improve" | "/app/api/ai-engine" | "/app/api/campaign" | "/app/api/keywords" | "/app/additional" | "/app/api/state" | "/app/campaigns" | "/app/api/scan" | "/app/api/sync" | "/app/keywords" | "/app/settings" | "/app/saved";
  };
  "routes/app.api.campaign-manage.js": {
    id: "routes/app.api.campaign-manage";
    page: "/app/api/campaign-manage";
  };
  "routes/app.api.campaign-status.js": {
    id: "routes/app.api.campaign-status";
    page: "/app/api/campaign-status";
  };
  "routes/app.api.store-analytics.js": {
    id: "routes/app.api.store-analytics";
    page: "/app/api/store-analytics";
  };
  "routes/app.api.market-intel.js": {
    id: "routes/app.api.market-intel";
    page: "/app/api/market-intel";
  };
  "routes/app.api.subscription.js": {
    id: "routes/app.api.subscription";
    page: "/app/api/subscription";
  };
  "routes/app.api.ai-improve.js": {
    id: "routes/app.api.ai-improve";
    page: "/app/api/ai-improve";
  };
  "routes/app.api.ai-engine.js": {
    id: "routes/app.api.ai-engine";
    page: "/app/api/ai-engine";
  };
  "routes/app.api.campaign.js": {
    id: "routes/app.api.campaign";
    page: "/app/api/campaign";
  };
  "routes/app.api.keywords.js": {
    id: "routes/app.api.keywords";
    page: "/app/api/keywords";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.api.state.js": {
    id: "routes/app.api.state";
    page: "/app/api/state";
  };
  "routes/app.campaigns.jsx": {
    id: "routes/app.campaigns";
    page: "/app/campaigns";
  };
  "routes/app.api.scan.js": {
    id: "routes/app.api.scan";
    page: "/app/api/scan";
  };
  "routes/app.api.sync.js": {
    id: "routes/app.api.sync";
    page: "/app/api/sync";
  };
  "routes/app.keywords.jsx": {
    id: "routes/app.keywords";
    page: "/app/keywords";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.saved.jsx": {
    id: "routes/app.saved";
    page: "/app/saved";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.products-delete": typeof import("./app/routes/webhooks.products-delete.jsx");
  "routes/CollectingDataScreen": typeof import("./app/routes/CollectingDataScreen.jsx");
  "routes/CompetitorComponents": typeof import("./app/routes/CompetitorComponents.jsx");
  "routes/LandingComponents": typeof import("./app/routes/LandingComponents.jsx");
  "routes/webhooks.products": typeof import("./app/routes/webhooks.products.jsx");
  "routes/DashboardWidgets": typeof import("./app/routes/DashboardWidgets.jsx");
  "routes/SmallComponents": typeof import("./app/routes/SmallComponents.jsx");
  "routes/AdPreviewPanel": typeof import("./app/routes/AdPreviewPanel.jsx");
  "routes/StoreAnalytics": typeof import("./app/routes/StoreAnalytics.jsx");
  "routes/styles.index": typeof import("./app/routes/styles.index.js");
  "routes/api.analyze": typeof import("./app/routes/api.analyze.js");
  "routes/api.credits": typeof import("./app/routes/api.credits.jsx");
  "routes/MarketAlert": typeof import("./app/routes/MarketAlert.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.api.campaign-manage": typeof import("./app/routes/app.api.campaign-manage.js");
  "routes/app.api.campaign-status": typeof import("./app/routes/app.api.campaign-status.js");
  "routes/app.api.store-analytics": typeof import("./app/routes/app.api.store-analytics.js");
  "routes/app.api.market-intel": typeof import("./app/routes/app.api.market-intel.js");
  "routes/app.api.subscription": typeof import("./app/routes/app.api.subscription.js");
  "routes/app.api.ai-improve": typeof import("./app/routes/app.api.ai-improve.js");
  "routes/app.api.ai-engine": typeof import("./app/routes/app.api.ai-engine.js");
  "routes/app.api.campaign": typeof import("./app/routes/app.api.campaign.js");
  "routes/app.api.keywords": typeof import("./app/routes/app.api.keywords.js");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.api.state": typeof import("./app/routes/app.api.state.js");
  "routes/app.campaigns": typeof import("./app/routes/app.campaigns.jsx");
  "routes/app.api.scan": typeof import("./app/routes/app.api.scan.js");
  "routes/app.api.sync": typeof import("./app/routes/app.api.sync.js");
  "routes/app.keywords": typeof import("./app/routes/app.keywords.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.saved": typeof import("./app/routes/app.saved.jsx");
};